### Numpy Arrays

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [3]:
a = np.array([[1, 2, 3], [5, 6, 7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [4]:
# min dimesions
a = np.array([1, 2, 3, 4, 5], ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [5]:
# dtype parameter
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


### Numpy Data Types

In [6]:
import numpy as np

In [7]:
dt = np.dtype(np.int32)
print(dt)

int32


In [8]:
# int8, int16, int32, int64 are equivalent to i1, i2, i3, i4

In [9]:
dt = np.dtype('i1')
print(dt)

int8


In [10]:
dt = np.dtype('i2')
print(dt)

int16


In [11]:
dt = np.dtype('i3')
print(dt)

TypeError: data type 'i3' not understood

In [12]:
dt = np.dtype('i4')
print(dt)

int32


In [13]:
dt = np.dtype('i8')
print(dt)

int64


In [14]:
# using endian notation
dt = np.dtype('>i4')
print(dt)

>i4


In [15]:
dt = np.dtype([('age', np.int8)])
print(dt)

[('age', 'i1')]


In [16]:
# applyin to ndarray
dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype=dt)
print(a)

[(10,) (20,) (30,)]


### Numpy Array Attributes

In [17]:
import numpy as np

In [18]:
# ndarray.shape
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

(2, 3)


In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.shape)

(3, 3)


In [20]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.shape = (3, 2)
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [21]:
# ndarray.ndim
a = np.array(24)
print(a)

24


In [22]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [23]:
a = np.arange(24)
print(a)
print(a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [25]:
a = np.arange(24)
print(a)
print(a.ndim)
b = a.reshape(2, 3, 4)
print(b)
print(b.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [26]:
# numpy.itemsize
x = np.array([1, 2, 3, 4, 5], dtype= np.int8)
print(x)

[1 2 3 4 5]


In [27]:
print(x.itemsize)

1


In [28]:
x = np.array([1, 2, 3, 4, 5], dtype = np.float32)
print(x)

[1. 2. 3. 4. 5.]


In [29]:
print(x.itemsize)

4


### Maths with Numpy

In [30]:
import numpy as np
import math as m

In [31]:
m.sqrt(81)

9.0

In [32]:
m.floor(7.2)

7

In [33]:
m.floor(7.8)

7

In [34]:
m.ceil(7.2)

8

In [35]:
m.sin(0)

0.0

In [36]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = ((a - b)**2).sum()
m.sqrt(c)

5.196152422706632